// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/KnightHacks/knighthacks_shared/models"
)

type Connection interface {
	IsConnection()
	GetTotalCount() *int
	GetPageInfo() *models.PageInfo
}

type Event struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	Description string    `json:"description"`
	Location    string    `json:"location"`
}

func (Event) IsEntity() {}

type EventsConnection struct {
	TotalCount int              `json:"totalCount"`
	PageInfo   *models.PageInfo `json:"pageInfo"`
	Events     []*Event         `json:"events"`
}

func (EventsConnection) IsConnection()                      {}
func (this EventsConnection) GetTotalCount() *int           { return &this.TotalCount }
func (this EventsConnection) GetPageInfo() *models.PageInfo { return this.PageInfo }

type NewEvent struct {
	Name        string    `json:"name"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	Description string    `json:"description"`
	Location    string    `json:"location"`
	HackathonID string    `json:"hackathonId"`
}

type UpdatedEvent struct {
	Name        *string    `json:"name,omitempty"`
	StartDate   *time.Time `json:"start_date,omitempty"`
	EndDate     *time.Time `json:"end_date,omitempty"`
	Description *string    `json:"description,omitempty"`
	Location    *string    `json:"location,omitempty"`
}
